### ISSUE TITLE
Banner colour is different 

### ISSUE THREAD

**Issue by dickieirwin** [victoriauniversity/vic-styles#24]
vic-styles/components/_components.banners.scss

Line 62 and 68

`background-color: rgba( $green-victoria-old, .75 );`

should be

`background-color: rgba( $green-victoria-study, .90 );`

**Comment by NeoGenet1c** [comment]
Has been refactored and fixed as a part of the broader refactoring in https://github.com/victoriauniversity/vic-styles/tree/v0.3.0
